### PR TITLE
Add deepcopy function to micro simulation cpp pybind wrapper

### PR DESCRIPTION
**Pull request by IshaanDesai**
Based on https://github.com/precice/micro-manager/pull/29.

### CODE REVIEW

**Comment by IshaanDesai** [comment]
The suggested change does not work, and produces the error:

```bash
/home/desaiin/dune-modules/dumux-adapter/examples/macro-micro/micro-heat/micro_sim.cpp:268:48: error: ‘__deepcopy__’ is not a member of ‘MicroSimulation’
  268 |         .def("__deepcopy__", &MicroSimulation::__deepcopy__);
      |                                                ^~~~~~~~~~~~
```
@erikscheurer any idea what is going wrong? Lets use this repository to test whatever we are changing in the Micro Manager.

**Comment by erikscheurer** [comment]
The class `MicroSimulation` needs to define the `__deepcopy__` function [in the header](https://github.com/precice/micro-manager/blob/b9ddb512d64a36647a3fdbc1cc1be1a36dea9b6e/examples/cpp-dummy/micro_cpp_dummy.hpp#L23) as well as implement it in the cpp file.
From how complex the microsimulation is, it might be hard to initialize a new Microsimulation every time we do a deep copy right? This is how it is done currently [in the dummy-PR](https://github.com/precice/micro-manager/blob/b9ddb512d64a36647a3fdbc1cc1be1a36dea9b6e/examples/cpp-dummy/micro_cpp_dummy.cpp#L73-L80)

**Comment by IshaanDesai** [comment]
Added it in the header part, and now got a undefined symbol error at runtime:

```bash
raceback (most recent call last):
  File "/home/desaiin/dune-modules/dumux-adapter/build-cmake/examples/macro-micro/micro-heat/run_micro_manager.py", line 7, in <module>
    manager = MicroManager("micro-manager-config.json")
  File "/home/desaiin/.local/lib/python3.10/site-packages/micro_manager/micro_manager.py", line 108, in __init__
    self._micro_problem = getattr(__import__(micro_file_name, fromlist=["MicroSimulation"]), "MicroSimulation")
ImportError: /home/desaiin/dune-modules/dumux-adapter/build-cmake/examples/macro-micro/micro-heat/micro_sim.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN15MicroSimulation12__deepcopy__Ev
(0) 10:52:12 [impl::SolverInterfaceImpl]:167 in ~SolverInterfaceImpl: Implicitly finalizing in destructor
```

**Comment by erikscheurer** [comment]
Because its not implemented yet, [here](https://github.com/precice/micro-manager/blob/b9ddb512d64a36647a3fdbc1cc1be1a36dea9b6e/examples/cpp-dummy/micro_cpp_dummy.cpp#L73-L80) the function is implemented for the dummies. As far as I know there is no c++ deepcopy function for classes like in python. But I would be happy to be wrong here.

**Comment by IshaanDesai** [comment]
> Because its not implemented yet, [here](https://github.com/precice/micro-manager/blob/b9ddb512d64a36647a3fdbc1cc1be1a36dea9b6e/examples/cpp-dummy/micro_cpp_dummy.cpp#L73-L80) the function is implemented for the dummies. As far as I know there is no c++ deepcopy function for classes like in python. But I would be happy to be wrong here.

I did assume that C++ would have something like this, and that is indeed an unreasonable assumption. I think we should handle this properly as is suggested in the pybind11 documentation: https://pybind11.readthedocs.io/en/latest/advanced/classes.html#deepcopy-support.

**Comment by IshaanDesai** [comment]
@HelenaKschidock in the micro code, we need to implement the `__deepcopy__` function which basically crates a new micro simulation object and then passes the state of the object to be copied from, to it. In the dummy this would look like:

https://github.com/precice/micro-manager/blob/ce5fed4a5448d8f3f629e9f27e6f0a0b1edf6aef/examples/cpp-dummy/micro_cpp_dummy.cpp#L72-L80

Can you implement something like this? I think its best if you do it as I do not know which DuMuX variables constitute the "state" of the micro simulation class.

**Comment by HelenaKschidock** [comment]
Yes will do

**Comment by HelenaKschidock** [comment]
Just so I understand: Instead of deepcopying the entire simulations, would it not be more efficient to simply repass the communicated values and demand a function similar to "reload_checkpoint()" (but with the inputs) from the user? What is the thought behind this?

**Comment by IshaanDesai** [comment]
> Just so I understand: Instead of deepcopying the entire simulations, would it not be more efficient to simply repass the communicated values and demand a function similar to "reload_checkpoint()" (but with the inputs) from the user? What is the thought behind this?

Which values do you mean by the communicated values here? The micro simulation is progressing in time, so unless we can fully define its state using some variables or some data, we have to do a deepcopy of the entire object. I cannot see how the `reload_checkpoint()` functionality could help us here. Could you please elaborate more?

Essentially what we want is the following: when an inactive simulation activates, it needs to get the *state* of the active simulation which it was copying data from, at the *current time*. To ensure this happens, we are doing a deepcopy of the active simulation and using it as the newly activated simulation.

**Comment by HelenaKschidock** [comment]
> > Just so I understand: Instead of deepcopying the entire simulations, would it not be more efficient to simply repass the communicated values and demand a function similar to "reload_checkpoint()" (but with the inputs) from the user? What is the thought behind this?
> 
> Which values do you mean by the communicated values here? The micro simulation is progressing in time, so unless we can fully define its state using some variables or some data, we have to do a deepcopy of the entire object. I cannot see how the `reload_checkpoint()` functionality could help us here. Could you please elaborate more?
> 
> Essentially what we want is the following: when an inactive simulation activates, it needs to get the _state_ of the active simulation which it was copying data from, at the _current time_. To ensure this happens, we are doing a deepcopy of the active simulation and using it as the newly activated simulation.

Isn't the whole point of the adaptivity that the full state of any micro simulation *is* in fact definable by its output, at least to a reasonable degree? Meaning we could feed the output of the active micro sim back into the previously inactive micro sims to reconstruct their state. in the next timestep when they are active again, they would then have a "previous"  state to use for time discretization etc.

**Comment by HelenaKschidock** [comment]
e.g. for the coupled heat micro problem, Phi (and the new macro temperature) would suffice, because the cell problem is stationary and all other values are either constant or derived, no?

**Comment by erikscheurer** [comment]
If I understand correctly, I agree with @HelenaKschidock here, if the state of the microproblem can be captured within a small number of variables, it would be much more efficient not to reinitialize the entire microproblem again. I would guess the `initialize` function takes a while to run?

If users have to implement a get and setState method anyways as implemented for https://github.com/precice/micro-manager/pull/30 then, we might be able to change the [`deepcopy`](https://github.com/precice/micro-manager/blob/2cf45530c921950db869035e34d54372bad5aa2e/micro_manager/adaptivity.py#L168) in the micromanager adaptivity to something like 
```python
if setState and getState exist:
	state = getState(micro_sims[associated_active_id])
	micro_sims[i].setState(state)
else:
	micro_sims[i] = deepcopy(micro_sims[associated_active_id])
```
One thing I don't know how its handled is the simulation time. If the simulation is inactive, the time is not increased right? This might then also have to be part of the state.

**Comment by IshaanDesai** [comment]
> Isn't the whole point of the adaptivity that the full state of any micro simulation is in fact definable by its output, at least to a reasonable degree? Meaning we could feed the output of the active micro sim back into the previously inactive micro sims to reconstruct their state. in the next timestep when they are active again, they would then have a "previous" state to use for time discretization etc.

No, the idea of adaptivity is to allow for micro simulations evolve in time and then use *some* of their output variables for the similarity calculation. If we were able to fully define the state of the micro simulation based on its output, we would not bother with storing the objects. But the micro simulation evolve in time. For example, the phase field value at each micro mesh point is unique each time, which defines the how the grain looks.

When an inactive simulation is activated again, we want it to take the state of its most similar active simulation *at the current time*, hence we do the deepcopy operation. Is this more clear now?

> e.g. for the coupled heat micro problem, Phi (and the new macro temperature) would suffice, because the cell problem is stationary and all other values are either constant or derived, no?

This will not work, because even though the cell problem is stationery, the Allen-Cahn problem is transient. So we need the micro phase field variable phi to be stored along with the macro Phi.

**Comment by HelenaKschidock** [comment]
Ah yes, you are of course correct. then even if we could recalculate the micro mesh phasefield via the analytic phasefield function, this would put more and more work into the user's court and possibly restrict other use cases. so deep copy it is, i will have a look on how to implement this in dumux

**Comment by IshaanDesai** [comment]
I like the idea that @erikscheurer has put forth though. Once we have the get- and set- state functions, we probably do not even need the deepcopy, as what we do there is essentially a deep copy.

> One thing I don't know how its handled is the simulation time. If the simulation is inactive, the time is not increased right? This might then also have to be part of the state.

Although the micro simulations are transient, they do not have a notion of absolute time. Timekeeping is the Micro Managers job (for now).

**Pull request merged**
